//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLYNHOMNGUOIDUNG
    {
        public string MANHANVIEN { get; set; }
        public string MANHOMNGUOIDUNG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
    }
}
