//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANGBANAN
    {
        public string MATINHTRANG { get; set; }
        public int MABANAN { get; set; }
        public string TENTINHTRANG { get; set; }
        public Nullable<System.DateTime> THOIGIANBATDAU { get; set; }
        public Nullable<System.DateTime> THOIGIANKETTHUC { get; set; }
    
        public virtual BANAN BANAN { get; set; }
    }
}
